name: shift_schedule
description: "A Flutter application for viewing your shift schedules and managing them."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  calendar_view: 1.4.0
  table_calendar: ^3.0.8
  material_symbols_icons: ^4.2815.1
  path_provider: ^2.0.11
  http: ^1.5.0
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  flutter_dotenv: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true